// Mocks generated by Mockito 5.4.4 from annotations
// in base_flutter/test/remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:base_flutter/core/services/remote/api_service.dart' as _i4;
import 'package:base_flutter/data/responses/login/login_response.dart' as _i2;
import 'package:base_flutter/data/responses/product/product_response.dart'
    as _i3;
import 'package:base_flutter/domain/request/login/login_request.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductResponse_1 extends _i1.SmartFake
    implements _i3.ProductResponse {
  _FakeProductResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceClient extends _i1.Mock implements _i4.ApiServiceClient {
  MockApiServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LoginResponse> login(_i6.LoginRequest? loginRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [loginRequest],
        ),
        returnValue: _i5.Future<_i2.LoginResponse>.value(_FakeLoginResponse_0(
          this,
          Invocation.method(
            #login,
            [loginRequest],
          ),
        )),
      ) as _i5.Future<_i2.LoginResponse>);

  @override
  _i5.Future<_i3.ProductResponse> getProducts() => (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue:
            _i5.Future<_i3.ProductResponse>.value(_FakeProductResponse_1(
          this,
          Invocation.method(
            #getProducts,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ProductResponse>);
}
