name: base_project_mvvm_provider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  get: ^4.6.5
  shared_preferences: ^2.0.18
  another_flushbar: ^1.12.29
  provider: ^6.0.5
  pretty_http_logger: ^0.2.2
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
