name: base_flutter
description: "Clean Architecture Design Pattern MVVM - Model - View - View Model Pattern ViewModel Inputs and Outputs Base ViewModel and Base UseCase Application Layer - Dependency Injection, Routes Manager and Application class Application Layer - Extensions and Shared Functions Data Layer - Data Sources (Remote Data Source/ Local Data Source) Data Layer - API Service Client (Same as Retorfit in Android) Data Layer - Calling APIs (Remote Data Source) Data Layer - Adding Logger Interceptor Data Layer - Caching APIs responses (Local Data Source) Data Layer - Json Serialization and Annotations Data Layer - Repository Implementation Data Layer - Mapper (Converting responses into Models) Data Layer - Mapper (Using toDomain Concept) Data Layer - Applying Null Safety Data Layer - Creating Mock APIs (Stub APIs) Domain Layer - Models Domain Layer - Repository Interfaces Domain Layer - UseCases Domain Layer - Either Concepts (Left - Failure) / (Right - Success) Domain Layer - Data Classes Presentation Layer - UI (Splash - Onboarding - Login - Register - Forgot Password - Main - Details - Settings - Notification - Search)) Presentation Layer - State Renderer (Full Screen States - Popup States) Presentation Layer - State Management (Stream Controller - RX Dart - Stream Builder) Presentation Layer - Localisations (English - Arabic), (RTL - LTR) Presentation Layer - Assets Manager (Android and Ios Icons and Images sizes) Presentation Layer - (Fonts - Styles - Themes - Strings - Values - Colors) Managers Presentation Layer - Using Json Animations Presentation Layer - Using SVG images Using 18 Flutter Packages Getting Device Info (Android - Ios) Using Abstract classes"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0-239.0.dev <4.0.0'

flavorizr:
  app:
    android:
      applicationId: "com.aigs.base"
    ios:
      bundleId: "com.aigs.base"
  flavors:
    sit:
      app:
        name: "Base Flutter SIT"
        android:
          applicationId: "com.aigs.base.sit"
        ios:
          bundleId: "com.aigs.base"
      environment:
        appConfig: "lib/config/config_sit.dart"
    uat:
      app:
        name: "Base Flutter UAT"
        android:
          applicationId: "com.aigs.base.uat"
        ios:
          bundleId: "com.aigs.base.uat"
      environment:
        appConfig: "lib/config/config_uat.dart"
    preprod:
      app:
        name: "Base Flutter PreProd"
        android:
          applicationId: "com.aigs.base.preprod"
        ios:
          bundleId: "com.aigs.base.preprod"
      environment:
        appConfig: "lib/config/config_preprod.dart"
    prod:
      app:
        name: "Base Flutter Prod"
        android:
          applicationId: "com.aigs.base.prod"
        ios:
          bundleId: "com.aigs.base.prod"
      environment:
        appConfig: "lib/config/config_prod.dart"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  json_serializable: ^6.1.5
  retrofit: ^4.4.0
  dio: ^5.7.0
  analyzer: ^6.9.0
  dartz: ^0.10.1
  internet_connection_checker: ^2.0.0
  pretty_dio_logger: ^1.2.0-beta-1
  shared_preferences: ^2.0.13
  freezed: ^2.5.7
  get_it: ^7.2.0
  lottie: ^3.1.2
  country_code_picker: ^3.0.0
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  carousel_slider: ^5.0.0
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.0.0
  http_parser: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  retrofit_generator: '>=8.0.0 <10.0.0'
  mockito: ^5.4.0
  flutter_flavorizr: ^2.0.1+2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
    - assets/translations/id-ID.json
    - assets/translations/en-US.json
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300

